fakeDatabase = [
    {"username": "Michael Scott", "password": "password"},
    {"username": "Jim Halpert", "password": "dragon"},
    {"username": "Pam Beesly", "password": "superman"},
    {"username": "Dwight Schrute", "password": "zoominfo"},
    {"username": "Kevin Malone", "password": "password5"},
    {"username": "Walter White", "password": "PureMeth"},
    {"username": "Jesse Pinkman", "password": "81207cH"},
    {"username": "Hank Schrader", "password": "DEA123"},
    {"username": "Gus Fring", "password": "El Pollero"},
    {"username": "Saul Goodman", "password": "BetterCallSaul"},
    {"username": "Skyler White", "password": "Marie"},
    {"username": "Paul Atreides", "password": "dune"},
    {"username": "John Doe", "password": "john123"},
    {"username": "Harry Potter", "password": "hogwarts"},
    {"username": "Hermione Granger", "password": "leviosa"},
    {"username": "Ron Weasley", "password": "quidditch"},
    {"username": "Jon Snow", "password": "winteriscoming"},
    {"username": "Arya Stark", "password": "valarmorghulis"},
    {"username": "Tony Stark", "password": "ironman"},
    {"username": "Peter Parker", "password": "spiderman"},
]